Added setters and implemented unit tests
vsfba1-iscteiul/ES1-2019-EIPL-81 pull request #14
Opened 2019-11-25 20:12 UTC by lrnsa-iscteiul

2019-11-26 09:26 UTC, djsar-iscteiul approved these changes

2019-11-26 16:01 UTC, vandabarata requested changes

2019-11-26 16:01 UTC, vandabarata commented on src/main/java/model/CodeQualityRule.java
> +			this.name = name;
else? should we present some kind of message to the user?

2019-11-26 16:01 UTC, vandabarata commented on src/main/java/model/CodeQualityRule.java
> +			this.rule = rule;
same as the name setter, I think we should have a way of showing the user they can't do what they're trying to do

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +	 * This test validates if the a default CodeQualityRule is being created successfully
```suggestion
	 * This test validates if a default CodeQualityRule is being created successfully
```

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +		assertEquals("is_long_method", ruleDefault .getName());
```suggestion
		assertEquals("is_long_method", ruleDefault.getName());
```

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +		assertEquals("is_long_method", ruleDefault .getName());
I know, I know, don't kill me :peace_symbol:

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +	 * This test validates if the a non default CodeQualityRule is being created successfully
```suggestion
	 * This test validates if a non default CodeQualityRule is being created successfully
```

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +		assertEquals("is_banana", ruleNonDefault .getName());
```suggestion
		assertEquals("is_banana", ruleNonDefault.getName());
```

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +	 * This test verifies if the content of a default rule can't be change with the
```suggestion
	 * This test verifies if the content of a default rule can't be changed with the 
```

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +		assertEquals("is_long_method", ruleDefault.getName());
I understand what you're doing here but I think we can separate these 3 tests - they're all for an advanced rule but they see different things, so we can't just aggregate them - since they're **unit** tests

2019-11-26 16:01 UTC, vandabarata commented on src/test/java/model/TestCodeQualityRuleModel.java
> +	 * This test verifies if the content of a default rule can be change with the
```suggestion
	 * This test verifies if the content of a default rule can be changed with the 
```

2019-11-26 16:01 UTC, vsfba1-iscteiul commented on src/test/java/model/TestCodeQualityRuleModel.java
> +		assertEquals("is_banana", ruleNonDefault.getName());
same as for the default - each of these "groups" of assertions should be its own unit test - that is

testNameChangeNonDefaultRule()
testRuleEditionNonDefaultRule()
testTypeChangeNonDefaultRule()

2019-11-26 16:01 UTC, vsfba1-iscteiul commented on src/test/java/model/TestCodeQualityRuleModel.java
> +		assertNotEquals(false, ruleNonDefault.isAdvanced());
unncessary and redundant since you already check if it's true in the above line

2019-11-26 16:01 UTC, vsfba1-iscteiul commented on src/test/java/model/TestCodeQualityRuleModel.java
> +		assertEquals(false, ruleDefault.isAdvanced());
redundant - if it's true, it's not false. no need to check for both results of a binary variable

2019-11-26 19:24 UTC, vsfba1-iscteiul commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) [Story] Classe para Regra](https://trello.com/c/N98sSJDY/6-1-story-classe-para-regra)

2019-11-26 19:25 UTC, vsfba1-iscteiul commented on src/main/java/model/CodeQualityRule.java
> +			this.name = name;
deprecated - that will be handled by the controller

2019-11-26 19:25 UTC, vsfba1-iscteiul commented on src/main/java/model/CodeQualityRule.java
> +			this.rule = rule;
deprecated - that will be handled by the controller

2019-11-27 00:06 UTC, vandabarata requested changes

2019-11-27 00:06 UTC, vsfba1-iscteiul commented on src/test/java/model/TestCodeQualityRuleModel.java
> +	void testRuleChangeDefaultRule() {
I get what you were going for mas acho que testRuleEditionDefaultRule() ficava mais fácil de perceber tbh

2019-11-27 00:06 UTC, vsfba1-iscteiul commented on src/test/java/model/TestCodeQualityRuleModel.java
> +	void testRuleChangeNonDefaultRule() {
same as before for the default rule - escrito só assim parece ser o tipo de regra, não necessariamente a edição do seu conteúdo

2019-11-27 09:34 UTC, vandabarata approved these changes

2019-11-27 09:36 UTC, merged