Feat gui excel popup
vsfba1-iscteiul/ES1-2019-EIPL-81 pull request #6
Opened 2019-11-09 17:00 UTC by djsar-iscteiul

I need to pull request, compare changes with the master branch and merge them.

2019-11-12 07:35 UTC, vandabarata requested changes

2019-11-12 07:35 UTC, vsfba1-iscteiul commented on src/main/java/controller/MainController.java
> +				JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
I think this should be a method defined somewhere else and just invoked here instead of defined here

2019-11-12 07:35 UTC, vsfba1-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> + * @version v1.0
Tira a versao please, ainda nao temos tags :p

2019-11-12 07:35 UTC, vsfba1-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +		panel.setLayout(new BorderLayout());
Podemos ter as identações iguais please? :')

2019-11-12 07:35 UTC, vsfba1-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +	public JButton getJButton() {
sorry, nao percebo para q precisamos disto

2019-11-12 21:02 UTC, vsfba1-iscteiul commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Task] Popup para escolher ficheiro](https://trello.com/c/z7m2vSgx/12-3-task-popup-para-escolher-ficheiro)

2019-11-13 18:17 UTC, djsar-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +	public JButton getJButton() {
Por que no ControllerMain eu irei precisar da instancia do JButton para fazer trigger a ação do botão.

2019-11-13 18:18 UTC, djsar-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +		panel.setLayout(new BorderLayout());
Sim claro master, já está :D

2019-11-13 18:18 UTC, djsar-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> + * @version v1.0
:D

2019-11-14 10:52 UTC, vandabarata requested changes

2019-11-14 10:52 UTC, vsfba1-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +	public JButton getJButton() {
que botão though? não há nome, isto não me dá nenhuma indicação do que estamos a trabalhar - tem que ter um nome, uma funcionalidade, algo.

2019-11-14 11:05 UTC, vsfba1-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +		JLabel label = new JLabel("Choose a file excel to import", SwingConstants.CENTER);
```suggestion
		JLabel label = new JLabel("Choose excel file to import", SwingConstants.CENTER);
```

2019-11-14 11:08 UTC, vsfba1-iscteiul commented on src/test/java/model/TestValidFormatFile.java
> +		String path_file = "C/Documents/file.xlsx";
```suggestion
		String path_file = "C://Documents/file.xlsx";
```

2019-11-14 11:08 UTC, vsfba1-iscteiul commented on src/test/java/model/TestValidFormatFile.java
> +		String path_file = "C/Documents/file.pptx";
```suggestion
		String path_file = "C://Documents/file.pptx";
```

2019-11-14 13:02 UTC, djsar-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +	public JButton getJButton() {
Alterei o nome para getImportJButton()

2019-11-14 13:04 UTC, djsar-iscteiul commented on src/main/java/gui/Popup_UploadFile.java
> +		JLabel label = new JLabel("Choose a file excel to import", SwingConstants.CENTER);
Done :D

2019-11-14 13:04 UTC, djsar-iscteiul commented on src/test/java/model/TestValidFormatFile.java
> +		String path_file = "C/Documents/file.xlsx";
Done :D

2019-11-14 13:04 UTC, djsar-iscteiul commented on src/test/java/model/TestValidFormatFile.java
> +		String path_file = "C/Documents/file.pptx";
Done :D

2019-11-14 14:59 UTC, vandabarata approved these changes

2019-11-14 15:00 UTC, merged